'use strict';

const { Octokit } = require('@octokit/rest');
const { loadRuntimeConfig } = require('../config');

let _octokit = null;
function getOctokit() {
  if (!_octokit) {
    const { githubToken } = loadRuntimeConfig();
    _octokit = new Octokit({ auth: githubToken });
  }
  return _octokit;
}

const MAX_FILES = 30;
const MAX_PATCH_CHARS = 20_000;
const MAX_TOTAL_CHARS = 90_000;
const MAX_FILE_CONTENT_SIZE = 100_000;
const MAX_FILE_LINES = 500;
const MAX_COMMENT_CHARS = 60_000;

const MARKER = '<!-- CLAUDE_PR_REVIEW -->';
const DISCLAIMER =
  '\n\n---\n' +
  '### 🤖 AI Peer Review Disclaimer\n' +
  '_This review was generated by Claude AI as an additional peer-review signal. ' +
  'It may be incomplete or incorrect. Always validate critical changes with human review and tests before merging._';

function makeError(code, message) {
  const err = new Error(message);
  err.code = code;
  return err;
}

function wrapOctokitError(err) {
  const status = err.status;
  if (status === 404) return makeError('NOT_FOUND', 'PR not found');
  if (status === 401 || status === 403) return makeError('GITHUB_AUTH', 'GitHub token invalid or insufficient permissions');
  if (status === 422) return makeError('GITHUB_VALIDATION', `GitHub validation error: ${err.message}`);
  if (status === 429) return makeError('RATE_LIMITED', 'GitHub API rate limit exceeded');
  if (err.code === 'ECONNREFUSED' || err.code === 'ENOTFOUND' || err.name === 'NetworkError') {
    return makeError('GITHUB_NETWORK', 'Cannot reach GitHub API');
  }
  return makeError('GITHUB_NETWORK', `GitHub API error: ${err.message}`);
}

async function getPRData(owner, repo, pull_number) {
  let prMeta, files;

  try {
    [{ data: prMeta }, files] = await Promise.all([
      getOctokit().pulls.get({ owner, repo, pull_number }),
      getOctokit().paginate(getOctokit().pulls.listFiles, { owner, repo, pull_number, per_page: 100 }),
    ]);
  } catch (err) {
    throw wrapOctokitError(err);
  }

  const headSha = prMeta.head.sha;
  const picked = files.slice(0, MAX_FILES).map(f => ({
    filename: f.filename,
    status: f.status,
    additions: f.additions,
    deletions: f.deletions,
    patch: f.patch ? f.patch.slice(0, MAX_PATCH_CHARS) : null,
    size: f.blob_url ? null : null, // will be set during content fetch
    fullContent: null,
  }));

  // Build diff summary
  const diffSummary = picked.map(f => {
    const header = `### ${f.filename} (${f.status}) +${f.additions}/-${f.deletions}`;
    const patch = f.patch
      ? `\n\`\`\`diff\n${f.patch}\n\`\`\`\n`
      : '\n(No patch available — file may be binary or too large.)\n';
    return `${header}${patch}`;
  }).join('\n');

  if (diffSummary.length > MAX_TOTAL_CHARS) {
    const err = new Error(`Diff is too large to review (${diffSummary.length} chars, max ${MAX_TOTAL_CHARS})`);
    err.code = 'DIFF_TOO_LARGE';
    throw err;
  }

  // Fetch full file content for each file (best-effort, failures don't abort)
  const contentResults = await Promise.allSettled(
    picked.map(f => fetchFileContent(owner, repo, f, headSha))
  );

  for (let i = 0; i < picked.length; i++) {
    const result = contentResults[i];
    if (result.status === 'fulfilled' && result.value !== null) {
      picked[i].fullContent = result.value;
    }
  }

  return {
    owner,
    repo,
    pull_number,
    title: prMeta.title,
    body: prMeta.body,
    pr_url: prMeta.html_url,
    headSha,
    author: prMeta.user.login,
    files: picked,
    diffSummary,
    files_reviewed: picked.length,
    total_diff_chars: diffSummary.length,
    files_truncated: files.length > MAX_FILES,
  };
}

async function fetchFileContent(owner, repo, file, ref) {
  // Skip deleted files and binary files
  if (file.status === 'removed') return null;
  if (!file.patch && file.status !== 'added' && file.status !== 'modified' && file.status !== 'renamed') return null;

  try {
    const { data } = await getOctokit().repos.getContent({ owner, repo, path: file.filename, ref });

    if (data.type !== 'file' || !data.content || data.encoding !== 'base64') return null;
    if (data.size > MAX_FILE_CONTENT_SIZE) return null;

    const content = Buffer.from(data.content, 'base64').toString('utf8');
    const lines = content.split('\n');

    if (lines.length <= MAX_FILE_LINES) return content;

    const half = Math.floor(MAX_FILE_LINES / 2);
    const omitted = lines.length - MAX_FILE_LINES;
    return [
      ...lines.slice(0, half),
      `... [${omitted} lines truncated] ...`,
      ...lines.slice(lines.length - half),
    ].join('\n');
  } catch {
    return null;
  }
}

async function deletePreviousBotComments(owner, repo, pull_number) {
  let comments;
  try {
    comments = await getOctokit().paginate(getOctokit().issues.listComments, {
      owner,
      repo,
      issue_number: pull_number,
      per_page: 100,
    });
  } catch (err) {
    console.warn('[github] Could not list comments for cleanup:', err.message);
    return 0;
  }

  let deleted = 0;
  for (const c of comments) {
    if (c.body && c.body.includes(MARKER)) {
      try {
        await getOctokit().issues.deleteComment({ owner, repo, comment_id: c.id });
        deleted++;
      } catch (err) {
        console.warn(`[github] Failed to delete comment ${c.id}:`, err.message);
      }
    }
  }

  return deleted;
}

async function postReview(owner, repo, pull_number, reviewText, inlineComments) {
  // Truncate review text if needed
  let body = reviewText;
  if (body.length > MAX_COMMENT_CHARS) {
    body = body.slice(0, MAX_COMMENT_CHARS) + '\n\n_(Truncated due to length.)_';
  }
  body = `${MARKER}\n${body}${DISCLAIMER}`;

  // Map inline comments to GitHub's shape
  const comments = inlineComments.map(c => ({
    path: c.path,
    line: c.line,
    side: 'RIGHT',
    body: c.body,
  }));

  // Try with inline comments first; fall back to summary only on validation error
  try {
    const { data } = await getOctokit().pulls.createReview({
      owner,
      repo,
      pull_number,
      body,
      event: 'COMMENT',
      comments: comments.length > 0 ? comments : undefined,
    });
    return { review_id: data.id, inline_comments_posted: comments.length };
  } catch (err) {
    if (err.status === 422 && comments.length > 0) {
      console.warn('[github] Inline comments rejected (invalid line positions), retrying without them');
      try {
        const { data } = await getOctokit().pulls.createReview({
          owner,
          repo,
          pull_number,
          body,
          event: 'COMMENT',
        });
        return { review_id: data.id, inline_comments_posted: 0 };
      } catch (err2) {
        throw wrapOctokitError(err2);
      }
    }
    throw wrapOctokitError(err);
  }
}

module.exports = { getPRData, deletePreviousBotComments, postReview };
