"""
GitHub service for PR data fetching and commenting
"""

import re
import logging
from typing import Dict, Any, List, Optional, Tuple
from github import Github, GithubIntegration
from github.PullRequest import PullRequest
from github.Repository import Repository

from app.config import RuntimeConfig

logger = logging.getLogger(__name__)

# Constants
MAX_FILES = 30
MAX_PATCH_CHARS = 20_000
MAX_TOTAL_CHARS = 90_000
MAX_FILE_CONTENT_SIZE = 100_000
MAX_FILE_LINES = 500
MAX_COMMENT_CHARS = 60_000

MARKER = '<!-- CLAUDE_PR_REVIEW -->'
DISCLAIMER = (
    '\n\n---\n'
    '### 🤖 AI Peer Review Disclaimer\n'
    '_This review was generated by Claude AI as an additional peer-review signal. '
    'It may be incomplete or incorrect. Always validate critical changes with human review and tests before merging._'
)

class GitHubServiceError(Exception):
    """Base exception for GitHub service errors"""
    def __init__(self, code: str, message: str):
        super().__init__(message)
        self.code = code

class GitHubService:
    """GitHub service for PR operations"""

    def __init__(self):
        self._github: Optional[Github] = None
        self._runtime_config: Optional[RuntimeConfig] = None

    def _get_github_client(self) -> Github:
        """Get or create GitHub client with app authentication"""
        if self._github is None:
            if self._runtime_config is None:
                self._runtime_config = RuntimeConfig.load()

            config = self._runtime_config
            logger.info(f"[github] initializing app auth appId={config.app_id} installationId={config.installation_id} privateKeyLength={len(config.private_key)}")

            integration = GithubIntegration(
                integration_id=config.app_id,
                private_key=config.private_key,
            )

            installation = integration.get_installation(config.installation_id)
            self._github = installation.get_github_for_installation()

        return self._github

    def _wrap_github_error(self, error: Exception) -> GitHubServiceError:
        """Wrap GitHub API errors with appropriate error codes"""
        error_str = str(error).lower()

        if "404" in error_str or "not found" in error_str:
            return GitHubServiceError("NOT_FOUND", "PR not found")
        elif "401" in error_str or "403" in error_str or "bad credentials" in error_str:
            return GitHubServiceError("GITHUB_AUTH", f"GitHub App auth failed: {error}")
        elif "422" in error_str or "validation" in error_str:
            return GitHubServiceError("GITHUB_VALIDATION", f"GitHub validation error: {error}")
        elif "429" in error_str or "rate limit" in error_str:
            return GitHubServiceError("RATE_LIMITED", "GitHub API rate limit exceeded")
        elif "connection" in error_str or "network" in error_str or "timeout" in error_str:
            return GitHubServiceError("GITHUB_NETWORK", f"GitHub API network error: {error}")
        else:
            return GitHubServiceError("GITHUB_NETWORK", f"GitHub API error: {error}")

    async def get_pr_data(self, owner: str, repo: str, pull_number: int) -> Dict[str, Any]:
        """
        Fetch PR data from GitHub

        Returns:
            Dict containing PR information and file changes
        """
        try:
            github_client = self._get_github_client()
            repository = github_client.get_repo(f"{owner}/{repo}")
            pr = repository.get_pull(pull_number)

            # Get PR basic info
            pr_data = {
                "title": pr.title,
                "author": pr.user.login if pr.user else "unknown",
                "pull_number": pull_number,
                "body": pr.body or "",
                "pr_url": pr.html_url,
                "headSha": pr.head.sha,
                "files_reviewed": 0,
                "total_diff_chars": 0,
                "files_truncated": 0,
                "files": [],
                "diffSummary": ""
            }

            # Get files
            files = list(pr.get_files())
            files_summary = []
            total_chars = 0
            files_reviewed = 0
            files_truncated = 0

            for file in files[:MAX_FILES]:
                if file.status == "removed":
                    continue

                patch = file.patch or ""
                patch_chars = len(patch)

                # Check size limits
                if patch_chars > MAX_PATCH_CHARS:
                    files_truncated += 1
                    continue

                if total_chars + patch_chars > MAX_TOTAL_CHARS:
                    files_truncated += 1
                    continue

                total_chars += patch_chars
                files_reviewed += 1

                # Get full file content if small enough
                full_content = None
                try:
                    if file.filename.endswith(('.py', '.js', '.ts', '.java', '.cpp', '.c', '.h', '.hpp', '.cs', '.php', '.rb', '.go', '.rs')):
                        content_file = repository.get_contents(file.filename, ref=pr.head.sha)
                        if hasattr(content_file, 'content') and content_file.size <= MAX_FILE_CONTENT_SIZE:
                            content = content_file.decoded_content.decode('utf-8')
                            lines = content.split('\n')
                            if len(lines) <= MAX_FILE_LINES:
                                full_content = content
                except Exception as e:
                    logger.warning(f"Could not fetch content for {file.filename}: {e}")

                file_data = {
                    "filename": file.filename,
                    "status": file.status,
                    "additions": file.additions,
                    "deletions": file.deletions,
                    "changes": file.changes,
                    "patch": patch,
                    "fullContent": full_content
                }

                pr_data["files"].append(file_data)

                # Add to summary
                summary_line = f"{file.filename} (+{file.additions} -{file.deletions})"
                files_summary.append(summary_line)

            pr_data["files_reviewed"] = files_reviewed
            pr_data["total_diff_chars"] = total_chars
            pr_data["files_truncated"] = files_truncated
            pr_data["diffSummary"] = "\n".join(files_summary)

            return pr_data

        except Exception as e:
            raise self._wrap_github_error(e)

    async def delete_previous_bot_comments(self, owner: str, repo: str, pull_number: int):
        """Delete previous bot comments from the PR"""
        try:
            github_client = self._get_github_client()
            repository = github_client.get_repo(f"{owner}/{repo}")
            pr = repository.get_pull(pull_number)

            # Get existing comments
            comments = list(pr.get_issue_comments())
            for comment in comments:
                if comment.body and MARKER in comment.body:
                    comment.delete()
                    logger.info(f"Deleted previous bot comment {comment.id}")

        except Exception as e:
            logger.warning(f"Could not delete previous comments: {e}")

    async def post_review(self, owner: str, repo: str, pull_number: int, head_sha: str,
                         review_text: str, inline_comments: List[Dict[str, Any]]) -> Dict[str, Any]:
        """
        Post review comments to GitHub PR

        Returns:
            Dict with review_id and inline_comments_posted count
        """
        try:
            github_client = self._get_github_client()
            repository = github_client.get_repo(f"{owner}/{repo}")
            pr = repository.get_pull(pull_number)

            # Prepare review body
            body = review_text
            if len(body) > MAX_COMMENT_CHARS:
                body = body[:MAX_COMMENT_CHARS - len(DISCLAIMER)] + "\n\n_(Review truncated)_"

            body += DISCLAIMER
            body += f"\n\n{MARKER}"

            # Create review
            review = pr.create_review(
                body=body,
                event="COMMENT",
                comments=[]  # We'll handle inline comments separately if needed
            )

            return {
                "review_id": review.id,
                "inline_comments_posted": 0  # Inline comments not implemented in this version
            }

        except Exception as e:
            raise self._wrap_github_error(e)

# Global service instance
github_service = GitHubService()